version: '3'
services:
  ud-parser:
    image: ayasaj/udify-http
    expose:
      - "8888"
  main:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/notebooks
    depends_on:
      - ud-parser
    deploy:
      resources:
        reservations:
          devices:
            - driver: 'nvidia'
              capabilities: ['gpu']
