version: '2'
services:
  ud-parser:
    image: ayasaj/udify-http
    ports:
      - 3000:8888
  main:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/notebooks
    depends_on:
      - udify
